In [1]:
import yfinance as yf
import pandas as pd
import numpy as np

multiple_df

In [2]:
tickers = ['AAPL', 'TSLA', 'JPM', 'ADBE', 'AMD', 'NVDA', 'AMZN',
           'FB', 'LRCX', 'MSFT', 'DPZ', 'MCD', 'CMG', 'LULU',
           'CRM', 'NOW', 'V', 'MA', 'AXP', 'GOOGL', 'NFLX', 'UNH',
           'ROG', 'HD', 'GD', 'FDX',  'COST', 'NKE']

In [3]:
multiple_df = yf.download(tickers, rounding=True)['Adj Close'][tickers].pct_change()

[*********************100%***********************]  28 of 28 completed

In [4]:
multiple_df.tail()

,AAPL,TSLA,JPM,ADBE,AMD,NVDA,AMZN,FB,LRCX,MSFT,...,AXP,GOOGL,NFLX,UNH,ROG,HD,GD,FDX,COST,NKE
Date,,,,,,,,,,,,,,,,,,,,,
2022-06-17,0.011533,0.017175,-0.003526,-0.011751,-0.005850,0.017883,0.024696,0.017840,0.002773,0.010940,...,0.048582,0.010468,0.012460,-0.008836,0.008947,-0.009983,-0.009958,0.020386,-0.011223,0.002054
2022-06-21,0.032761,0.093544,0.024772,0.006098,0.027216,0.043199,0.023159,-0.040857,0.032375,0.024591,...,0.004023,0.041071,-0.026209,0.062514,-0.000810,-0.005651,0.032272,0.002711,0.036759,0.012484
2022-06-22,-0.003827,-0.004008,-0.005612,0.006446,-0.000477,-0.012435,0.002484,-0.007641,-0.017112,-0.002404,...,-0.002556,-0.000507,0.046691,0.019487,0.001582,-0.000817,-0.002494,-0.006496,-0.006802,-0.034597
2022-06-23,0.021574,-0.004306,-0.010939,0.030958,-0.015761,-0.008252,0.032033,0.018608,-0.003642,0.022637,...,-0.018976,0.006768,0.015764,0.020687,0.002157,0.023942,0.002731,-0.003906,0.032698,0.029356
2022-06-24,0.024517,0.045249,0.029846,0.029418,0.056412,0.055532,0.035752,0.071874,0.061569,0.034150,...,0.031768,0.051077,0.050300,-0.008343,-0.002345,0.027522,0.026454,0.071636,0.019726,0.045463

In [5]:
multiple_df = multiple_df.reset_index(drop=True)

In [6]:
multiple_df.tail()

,AAPL,TSLA,JPM,ADBE,AMD,NVDA,AMZN,FB,LRCX,MSFT,...,AXP,GOOGL,NFLX,UNH,ROG,HD,GD,FDX,COST,NKE
15221,0.011533,0.017175,-0.003526,-0.011751,-0.005850,0.017883,0.024696,0.017840,0.002773,0.010940,...,0.048582,0.010468,0.012460,-0.008836,0.008947,-0.009983,-0.009958,0.020386,-0.011223,0.002054
15222,0.032761,0.093544,0.024772,0.006098,0.027216,0.043199,0.023159,-0.040857,0.032375,0.024591,...,0.004023,0.041071,-0.026209,0.062514,-0.000810,-0.005651,0.032272,0.002711,0.036759,0.012484
15223,-0.003827,-0.004008,-0.005612,0.006446,-0.000477,-0.012435,0.002484,-0.007641,-0.017112,-0.002404,...,-0.002556,-0.000507,0.046691,0.019487,0.001582,-0.000817,-0.002494,-0.006496,-0.006802,-0.034597
15224,0.021574,-0.004306,-0.010939,0.030958,-0.015761,-0.008252,0.032033,0.018608,-0.003642,0.022637,...,-0.018976,0.006768,0.015764,0.020687,0.002157,0.023942,0.002731,-0.003906,0.032698,0.029356
15225,0.024517,0.045249,0.029846,0.029418,0.056412,0.055532,0.035752,0.071874,0.061569,0.034150,...,0.031768,0.051077,0.050300,-0.008343,-0.002345,0.027522,0.026454,0.071636,0.019726,0.045463

In [7]:
multiple_df2 = multiple_df * multiple_df

result = pd.concat([multiple_df, multiple_df, multiple_df], axis=1)

In [8]:
multiple_df2

,AAPL,TSLA,JPM,ADBE,AMD,NVDA,AMZN,FB,LRCX,MSFT,...,AXP,GOOGL,NFLX,UNH,ROG,HD,GD,FDX,COST,NKE
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.003086,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15221,0.000133,0.000295,0.000012,0.000138,3.422357e-05,0.000320,0.000610,0.000318,0.000008,0.000120,...,0.002360,1.095872e-04,0.000155,0.000078,8.004221e-05,9.966385e-05,0.000099,0.000416,0.000126,0.000004
15222,0.001073,0.008751,0.000614,0.000037,7.407046e-04,0.001866,0.000536,0.001669,0.001048,0.000605,...,0.000016,1.686834e-03,0.000687,0.003908,6.554893e-07,3.193817e-05,0.001041,0.000007,0.001351,0.000156
15223,0.000015,0.000016,0.000031,0.000042,2.278954e-07,0.000155,0.000006,0.000058,0.000293,0.000006,...,0.000007,2.565692e-07,0.002180,0.000380,2.502639e-06,6.678751e-07,0.000006,0.000042,0.000046,0.001197
15224,0.000465,0.000019,0.000120,0.000958,2.484152e-04,0.000068,0.001026,0.000346,0.000013,0.000512,...,0.000360,4.580007e-05,0.000248,0.000428,4.654077e-06,5.732338e-04,0.000007,0.000015,0.001069,0.000862
15225,0.000601,0.002047,0.000891,0.000865,3.182257e-03,0.003084,0.001278,0.005166,0.003791,0.001166,...,0.001009,2.608874e-03,0.002530,0.000070,5.498515e-06,7.574387e-04,0.000700,0.005132,0.000389,0.002067